ShangOnline/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
import xadmin
from django.views.static import serve
from ShangOnline.settings import MEDIA_ROOT,STATIC_ROOT
from users.views import IndexView

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^$',IndexView.as_view(),name='index'),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^static/(?P<path>.*)', serve, {'document_root': STATIC_ROOT}),
    url(r'^static/media/(?P<path>.*)',serve,{'document_root':MEDIA_ROOT}),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^orgs/', include('orgs.urls', namespace='orgs')),
    url(r'^operations/', include('operations.urls', namespace='operations')),

]

apps/courses/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import course_list,course_detail,course_video,course_comment
urlpatterns = [
    url(r'^course_list/$',course_list,name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

apps/operations/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import user_ask,user_love,user_comment,user_deletelove
urlpatterns = [
    url(r'^user_ask/$',user_ask,name='user_ask'),
    url(r'^user_love/$', user_love, name='user_love'),
    url(r'^user_comment/$', user_comment, name='user_comment'),
    url(r'^user_deletelove/$', user_deletelove, name='user_deletelove'),
]

apps/orgs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .views import org_list,org_detail,org_detail_course,org_detail_desc,org_detail_teacher,teacher_list,teacher_detail

urlpatterns = [
    url(r'^org_list/$',org_list,name='org_list'),
    url(r'^org_detail/(\d+)/$', org_detail, name='org_detail'),
    url(r'^org_detail_course/(\d+)/$', org_detail_course, name='org_detail_course'),
    url(r'^org_detail_desc/(\d+)/$', org_detail_desc, name='org_detail_desc'),
    url(r'^org_detail_teacher/(\d+)/$', org_detail_teacher, name='org_detail_teacher'),


    url(r'^teacher_list/$',teacher_list,name='teacher_list'),
    url(r'^teacher_detail/(\d+)/$', teacher_detail, name='teacher_detail'),
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/courses/models.py
from django.db import models
from datetime import datetime
from orgs.models import OrgInfo,TeacherInfo
from DjangoUeditor.models import UEditorField
# Create your models here.
class CourseInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="课程名称")
    desc = models.CharField(max_length=200,verbose_name="课程简介")
    detail = UEditorField(verbose_name='课程详情', width=700, height=400, toolbars='full',
                          imagePath='ueditor/images/', filePath='ueditor/files/',
                          upload_settings={'imageMaxSizing': 1024000},
                          default='')
    level = models.CharField(choices=(('初级','初级'),('中级','中级'),('高级','高级')),max_length=5,verbose_name="课程难度",default='初级')
    stunum = models.IntegerField(default=0,verbose_name="学习人数")
    study_time = models.IntegerField(default=0,verbose_name="学习时长")
    lesson_num = models.IntegerField(default=0,verbose_name="章节数")
    category = models.CharField(choices=(('前端','前端'),('后台','后台')),max_length=5,verbose_name="课程类别")
    click_num = models.IntegerField(default=0, verbose_name='点击数')
    love_num = models.IntegerField(default=0, verbose_name='收藏数')
    image = models.ImageField(upload_to='course/%y/%m',verbose_name="课程图片",max_length=100)
    orginfo = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    teacherinfo = models.ForeignKey(TeacherInfo,verbose_name="所属讲师")
    need_know = models.CharField(max_length=100,verbose_name="课程须知",null=True,blank=True)
    teacher_say = models.CharField(max_length=200,verbose_name="老师告知",null=True,blank=True)
    is_banner = models.BooleanField(default=False,verbose_name="是否轮播")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = '课程信息'
        verbose_name_plural = verbose_name

class LessonInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="章节名称")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '章节信息'
        verbose_name_plural = verbose_name

class VideoInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="视频名称")
    study_time = models.IntegerField(default=0,verbose_name='视频时长')
    url = models.URLField(default='http://video.atguigu.com/ce182d3e92d24c08ada798ed75236efe/64240d5f98c849d7a48a701646314ef0-abb0a550e0a4e1bd89390a178f91a577-ld.mp4',max_length=200,verbose_name='视频连接')
    lessoninfo = models.ForeignKey(LessonInfo,verbose_name="所属章节")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name

class SourceInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="资源名称")
    file_addr = models.FileField(upload_to='source/%y/%m',verbose_name="资源地址",max_length=200)
    courseinfo = models.ForeignKey(CourseInfo,verbose_name='所属课程')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '资源信息'
        verbose_name_plural = verbose_name

apps/operations/models.py
from django.db import models
from datetime import datetime
from users.models import UserProfile
from courses.models import CourseInfo
# Create your models here.
class UserAskInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="咨询姓名")
    phone = models.CharField(max_length=11,verbose_name="咨询手机")
    course = models.CharField(max_length=20,verbose_name="咨询课程")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '用户咨询信息'
        verbose_name_plural = verbose_name

class UserLoveInfo(models.Model):
    userinfo = models.ForeignKey(UserProfile,verbose_name="所属用户")
    love_id = models.IntegerField(verbose_name="收藏id")
    love_type = models.IntegerField(choices=((1,'收藏机构'),(2,'收藏课程'),(3,'收藏讲师')),verbose_name="收藏类别")
    love_status = models.BooleanField(default=False,verbose_name='收藏状态')
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.userinfo.username

    class Meta:
        verbose_name = '用户收藏信息'
        verbose_name_plural = verbose_name


class UserCourseInfo(models.Model):
    userinfo = models.ForeignKey(UserProfile, verbose_name="所属用户")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.userinfo.username

    class Meta:
        unique_together = ('userinfo','courseinfo')
        verbose_name = '用户所学课程信息'
        verbose_name_plural = verbose_name

class UserMessageInfo(models.Model):
    userinfo = models.IntegerField(default=0,verbose_name='所属用户')
    message = models.CharField(max_length=200,verbose_name='消息内容')
    msg_status = models.BooleanField(default=False,verbose_name="是否已读")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = '用户消息信息'
        verbose_name_plural = verbose_name


class UserCommentInfo(models.Model):
    userinfo = models.ForeignKey(UserProfile, verbose_name="所属用户")
    courseinfo = models.ForeignKey(CourseInfo,verbose_name="所属课程")
    comment_content = models.CharField(max_length=200,verbose_name="评论内容")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.comment_content

    class Meta:
        verbose_name = '用户评论信息'
        verbose_name_plural = verbose_name


apps/orgs/models.py
from django.db import models
from datetime import datetime
from DjangoUeditor.models import UEditorField
# Create your models here.
class CityInfo(models.Model):
    name = models.CharField(max_length=50,verbose_name="城市名称")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '城市信息'
        verbose_name_plural = verbose_name


class OrgInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="机构名称")
    image = models.ImageField(upload_to='org/%y/%m',verbose_name="机构图片",max_length=100)
    study_num = models.IntegerField(default=0,verbose_name="学习人数")
    address = models.CharField(max_length=200,verbose_name="机构地址")
    click_num = models.IntegerField(default=0,verbose_name="点击数")
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    desc = models.CharField(max_length=200,verbose_name='机构简介')
    detail = UEditorField(verbose_name='机构详情',width=700,height=400,toolbars='full',imagePath='ueditor/images/',filePath='ueditor/files/',upload_settings={'imageMaxSizing':1024000},default='')
    course_num = models.IntegerField(default=0,verbose_name="课程数量")
    cityinfo = models.ForeignKey(CityInfo,verbose_name='所属城市')
    category = models.CharField(choices=(('jg','机构'),('gx','高校'),('gr','个人')),max_length=5,verbose_name="机构类别",null=True,blank=True)
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '机构信息'
        verbose_name_plural = verbose_name


class TeacherInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="讲师姓名")
    image = models.ImageField(upload_to='teacher/%y/%m',verbose_name="讲师头像",null=True,blank=True,max_length=200)
    work_year = models.IntegerField(default=3,verbose_name="工作年限")
    work_company = models.CharField(max_length=20,verbose_name="就职公司",null=True,blank=True)
    work_position = models.CharField(max_length=20,verbose_name="工作职位",null=True,blank=True)
    age = models.IntegerField(default=30,verbose_name="讲师年龄")
    work_style = models.CharField(max_length=20,verbose_name="教学特点",null=True,blank=True)
    click_num = models.IntegerField(default=0, verbose_name="点击数")
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    orginfo = models.ForeignKey(OrgInfo,verbose_name="所属机构")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '讲师信息'
        verbose_name_plural = verbose_name




apps/courses/views.py
from django.shortcuts import render
from .models import CourseInfo
from operations.models import UserLoveInfo,UserCourseInfo,UserCommentInfo
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from helptools.decorators import login_decorator
from django.db.models import Q
# Create your views here.
def course_list(request):
    all_courses = CourseInfo.objects.all()
    rec_courses = all_courses.order_by('-love_num')[:3]

    keywords = request.GET.get('keywords','')
    if keywords:
        all_courses = all_courses.filter(Q(name__icontains=keywords)|Q(desc__icontains=keywords)|Q(detail__icontains=keywords))

    sort_type = request.GET.get('sort','')
    if sort_type == 'hot':
        all_courses = all_courses.order_by('-click_num')
    if sort_type == 'students':
        all_courses = all_courses.order_by('-stunum')

    pagenum = request.GET.get('pagenum', 1)
    pa = Paginator(all_courses, 2)
    try:
        page_list = pa.page(pagenum)
    except PageNotAnInteger:
        page_list = pa.page(1)
    except EmptyPage:
        page_list = pa.page(pa.num_pages)

    return render(request,'courses/course-list.html',{
        'all_courses':all_courses,
        'sort_type':sort_type,
        'page_list':page_list,
        'rec_courses':rec_courses,
        'keywords': keywords
    })

def course_detail(request,course_id):
    '''

    :param request:
    :param course_id:
    :return:
    '''
    if course_id:
        all_courses = CourseInfo.objects.all()
        course = CourseInfo.objects.filter(id = int(course_id))[0]
        rec_courses = all_courses.filter(name__icontains=course.name[:4])
        course.click_num += 1
        course.save()

        is_love = False
        is_loveCourse = False
        if request.user.is_authenticated():
            love = UserLoveInfo.objects.filter(userinfo=request.user, love_type=1, love_id=course.orginfo.id)
            love1 = UserLoveInfo.objects.filter(userinfo=request.user, love_type=2, love_id=course.id)
            if love:
                is_love = love[0].love_status
            else:
                pass

            if love1:
                is_loveCourse = love1[0].love_status
            else:
                pass
        return render(request,'courses/course-detail.html',{
            'course':course,
            'rec_courses':rec_courses,
            'is_love':is_love,
            'is_loveCourse':is_loveCourse
        })

@login_decorator
def course_video(request,course_id):
    if course_id:
        course = CourseInfo.objects.filter(id = int(course_id))[0]
        #这个逻辑是用来判断用户学习课程的表当中是否学习过这个课程，如果没有学习过就添加记录
        usercourse = UserCourseInfo.objects.filter(userinfo=request.user, courseinfo_id=int(course_id))
        if not usercourse:
            a = UserCourseInfo()
            a.userinfo = request.user
            a.courseinfo =course
            a.save()
            #如果有人最新学习这门课程，就让课程学习人数加1
            course.stunum += 1
            course.save()
            #课程的学习人数加1，那么这个课程所属机构学习人数就加1
            course.orginfo.study_num+=1
            course.orginfo.save()

        #这个逻辑是用来找到学过该课程的学生还学过的课程
        #第一步，找到所有有关这个课程的 用户课程对象
        usercourseobjs = UserCourseInfo.objects.filter(courseinfo=course)
        #第二步，通过这个所有的用户课程对象，可以实现找到所有的学过这个课程的用户
        userids_list = [usercourse.userinfo_id  for usercourse in usercourseobjs]
        #第三步，通过遍历这所有的用户，找到所有用户课程
        usercourse_list = UserCourseInfo.objects.filter(userinfo_id__in=userids_list)
        #第四步，通过第三步找到的用户课程去拿课程
        course_list = [usercourse.courseinfo  for usercourse in usercourse_list]
        #第五步，为了防止重复，我们可以使用集合去重
        course_list = list(set(course_list))
        course_list = [ course1 for course1 in course_list if course1.id != course.id][:3]


        return render(request, 'courses/course-video.html', {
                'course': course,
                'course_list':course_list
            })

def course_comment(request,course_id):
    if course_id:
        course = CourseInfo.objects.filter(id=int(course_id))[0]
        # 这个逻辑是用来找到学过该课程的学生还学过的课程
        # 第一步，找到所有有关这个课程的 用户课程对象
        usercourseobjs = UserCourseInfo.objects.filter(courseinfo=course)
        # 第二步，通过这个所有的用户课程对象，可以实现找到所有的学过这个课程的用户
        userids_list = [usercourse.userinfo_id for usercourse in usercourseobjs]
        # 第三步，通过遍历这所有的用户，找到所有用户课程
        usercourse_list = UserCourseInfo.objects.filter(userinfo_id__in=userids_list)
        # 第四步，通过第三步找到的用户课程去拿课程
        course_list = [usercourse.courseinfo for usercourse in usercourse_list]
        # 第五步，为了防止重复，我们可以使用集合去重
        course_list = list(set(course_list))
        course_list = [course1 for course1 in course_list if course1.id != course.id][:3]

        all_comment = UserCommentInfo.objects.filter(courseinfo=course)

        return render(request,'courses/course-comment.html',{
            'course': course,
            'course_list': course_list,
            'all_comment':all_comment
        })

templates/courses/course-list.html
{% extends 'base.html' %}
{% block title %}公开课列表 - 尚在线{% endblock %}
{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li {% if sort_type == '' %}class="active"{% endif %}><a href="?sort=">最新 </a></li>
						<li {% if sort_type == 'hot' %}class="active"{% endif %}><a href="?sort=hot">最热门</a></li>
						<li {% if sort_type == 'students' %}class="active"{% endif %}><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                        {% for course in page_list %}
                            <div class="box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.study_time }}</i></span>
                                    <span class="fr">学习人数：{{ course.stunum }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'courses:course_detail' course.id %}"><span class="fl">来自{{ course.orginfo.name }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.love_num }}
                                    </span>
                                </div>
                            </div>
                        {% endfor %}
					</div>
                    <div class="pageturn">
                        <ul class="pagelist">

                {% if page_list.has_previous %}
                <li class="long"><a href="?pagenum={{ page_list.previous_page_number }}&sort={{ sort_type }}&keywords={{ keywords }}">上一页</a></li>
                {% else %}
                <li class="long"><a href="?pagenum=1&sort={{ sort_type }}&keywords={{ keywords }}">上一页</a></li>
                {% endif %}

                {% for num in page_list.paginator.page_range %}
                <li {% if num == page_list.number %}class="active"{% endif %}><a href="?pagenum={{ num }}&sort={{ sort_type }}&keywords={{ keywords }}">{{ num }}</a></li>
                {% endfor %}


                {% if page_list.has_next %}
                <li class="long"><a href="?pagenum={{ page_list.next_page_number }}&sort={{ sort_type }}&keywords={{ keywords }}">下一页</a></li>
                {% else %}
                <li class="long"><a href="?pagenum={{ page_list.paginator.num_pages }}&sort={{ sort_type }}&keywords={{ keywords }}">下一页</a></li>
                {% endif %}



            </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">
                {% for course in rec_courses %}
                    <dl>
						<dt>
							<a target="_blank" href="{% url 'courses:course_detail' course.id %}">
								<img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href="{% url 'courses:course_detail' course.id %}"><h2> {{ course.name }}</h2></a>
							<span class="fl">难度：<i class="key">{{ course.level }}</i></span>
						</dd>
					</dl>
                {% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}




templates/courses/course-video.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}公开课视频信息 - 尚在线{% endblock %}
{% block mycss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}

{% block content %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'courses:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a>></li>
                <li>章节信息</li>
			</ul>
		</div>
	</div>
</section>
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.level }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.study_time }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.stunum }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'courses:course_video' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'courses:course_comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                </div>

                <div class="mod-chapters">
                    {% for lesson in course.lessoninfo_set.all %}
                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>
                        <ul class="video">
                            {% for video in lesson.videoinfo_set.all %}
                            <li>
                                <a target="_blank" href='{{ video.url }}' class="J-media-item studyvideo">{{ video.name }}({{ video.study_time }})
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}
                    
                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                           {% for source in course.sourceinfo_set.all %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ source.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ source.file_addr }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacherinfo.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="{% url 'orgs:teacher_detail' course.teacherinfo.id %}?sort=publish" target="_blank">{{ course.teacherinfo.name }}</a>
        </span>
                            <span class="job">{{ course.teacherinfo.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.need_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_say }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for course1 in course_list %}
                                    <li class="curr">
                                        <a href="{% url 'courses:course_detail' course1.id %}" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ course1.image }}" >
                                            <span class="name autowrap">{{ course1.name }}</span>
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}